### ISSUE TITLE
怎么编译libffi的库，可以提供一下指南吗，谢谢

### ISSUE THREAD

**Issue by allanGoldZhiKang** [eleme/Stinger#5]
怎么编译libffi的库，可以提供一下指南吗，谢谢

**Comment by Assuner-Lee** [comment]
https://github.com/libffi/libffi  使用cmake

**Comment by allanGoldZhiKang** [comment]
> https://github.com/libffi/libffi 使用cmake

我知道用cmake，能提供一下具体的步骤，更好
